LIBDRUM-1038. Fixes for Angular compile errors
Fixed Angular compile errors when running `npm run start:dev`.

* /src/themes/drum/app/home-page/home-page.component.ts

    ```
    Error: src/themes/drum/app/home-page/home-page.component.ts:13:43 - error TS2307: Cannot find module 'src/app/notifications/suggestions-popup/suggestions-popup.component' or its corresponding type declarations.

    13 import { SuggestionsPopupComponent } from 'src/app/notifications/suggestions-popup/suggestions-popup.component';
    ```

    Component was moved to a "popup" subfolder:
    `src/app/notifications/suggestions/popup/suggestions-popup.component`
    so simply updated the import.

* src/themes/drum/app/home-page/home-news/home-news.component.scss

    ```
    ./src/app/home-page/home-news/home-news.component.scss?ngResource - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
    SassError: Undefined mixin.
       ╷
    65 │ ┌   @include hover {
    66 │ │     color: var(--ds-home-news-link-hover-color);
    67 │ └   }
      ╵
     src/app/home-page/home-news/home-news.component.scss 65:3  root stylesheet
    ```

    Fixed by changing @include hover to simply &:hover.

    This was due to the Bootstrap 4 to Bootstrap 5 update, which removed
    the “hover” mixin.

https://umd-dit.atlassian.net/browse/LIBDRUM-1038